# Generated by Django 3.2.7 on 2021-09-28 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('posted_on', models.DateTimeField(auto_now_add=True, verbose_name='Posted On')),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.instituteclass')),
                ('user_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_day', models.DateField(verbose_name='Day')),
                ('start_time', models.TimeField(verbose_name='Start')),
                ('end_time', models.TimeField(verbose_name='End')),
                ('posted_on', models.DateTimeField(auto_now_add=True, verbose_name='Posted On')),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.instituteclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.subject')),
                ('user_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
    ]
