# Generated by Django 3.2.7 on 2021-09-28 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute.instituteclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('posted_on', models.DateTimeField(auto_now_add=True, verbose_name='Posted On')),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute.instituteclass')),
                ('user_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='ExamAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to='exam/answers', verbose_name='Exam Answer')),
                ('posted_on', models.DateField(auto_now_add=True, verbose_name='Posted On')),
                ('exam_qus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ExamAns',
                'verbose_name_plural': "ExamAns's",
            },
        ),
    ]
