# Generated by Django 3.2.7 on 2021-09-28 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_type', models.CharField(blank=True, max_length=50, verbose_name='Institute Type')),
                ('institute_phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('institute_short_desc', tinymce.models.HTMLField()),
                ('profile_img', models.ImageField(null=True, upload_to='media/institute/profile_imgs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.CharField(max_length=50, verbose_name='Class')),
                ('user_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Subject')),
                ('subject_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.instituteclass')),
                ('subject_of_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.instituteclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('works_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=150, verbose_name='Fathers Name')),
                ('mothers_name', models.CharField(max_length=150, verbose_name='Mothers Name')),
                ('roll', models.IntegerField(verbose_name='Roll')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.instituteclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=250, verbose_name='Title')),
                ('notice_content', tinymce.models.HTMLField()),
                ('notice_img', models.ImageField(null=True, upload_to='media/institute/Notice_imgs/')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=50, verbose_name='Applicant')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('previous_institute', models.CharField(blank=True, default=None, max_length=50, verbose_name='Previous Institute')),
                ('previous_class', models.CharField(blank=True, default=None, max_length=50, verbose_name='Previous Class')),
                ('applied_on', models.DateTimeField(auto_now_add=True, verbose_name='Applied On')),
                ('applied_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.instituteclass')),
                ('applied_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
        ),
    ]
